# general settings
name: 003_StyleGAN2_512_Cmul1_CCPD_280k_B8G2_scratch_continue_train
model_type: StyleGAN2Model
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: CCPD
    type: CCPDDataset
    dataroot_gt: datasets/ccpd/ccpd_crop_rect_PerspectiveTransform_front_50000_realesr_512
    io_backend:
      type: disk

    use_hflip: false
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# network structures
network_g:
  type: StyleGAN2Generator
  out_size: 512
  num_style_feat: 512
  num_mlp: 8
  channel_multiplier: 1
  resample_kernel: [1, 3, 3, 1]
  lr_mlp: 0.01

network_d:
  type: StyleGAN2Discriminator
  out_size: 512
  channel_multiplier: 1
  resample_kernel: [1, 3, 3, 1]

# path
path:
  # pretrain_network_g: experiments/003_StyleGAN2_512_Cmul1_CCPD_280k_B8G2_scratch/models/net_g_100000.pth
  strict_load_g: true
  # resume_state: experiments/003_StyleGAN2_512_Cmul1_CCPD_280k_B8G2_scratch_continue_train/training_states/150000.state
  # pretrain_network_d: experiments/003_StyleGAN2_512_Cmul1_CCPD_280k_B8G2_scratch/models/net_d_100000.pth

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-3

  optim_d:
    type: Adam
    lr: !!float 2e-3

  scheduler:
    type: MultiStepLR
    milestones: [110000]
    gamma: 0.5

  total_iter: 280000
  warmup_iter: -1  # no warm up

  # losses
  gan_opt:
    type: GANLoss
    gan_type: wgan_softplus
    loss_weight: !!float 1
  # r1 regularization for discriminator
  r1_reg_weight: 10
  # path length regularization for generator
  path_batch_shrink: 2
  path_reg_weight: 2

  net_g_reg_every: 4
  net_d_reg_every: 16
  mixing_prob: 0.9

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: 003_StyleGAN2_512_Cmul1_CCPD_280k_B8G2_scratch_continue_train

# dist training settings
dist_params:
  backend: nccl
  port: 29500
